//===- TileLangOps.cpp - TileLang operation verifiers ----------*- C++ -*-===//
//
// Hand-written operation verifiers and additional methods for TileLang ops.
// The op class skeletons are generated by mlir-tblgen from TileLangOps.td
// and included via TileLangOps.h. This file adds custom verification logic
// that cannot be expressed in TableGen alone.
//
//===----------------------------------------------------------------------===//

#include "TileLang/IR/TileLangOps.h"
#include "TileLang/IR/TileLangDialect.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpImplementation.h"

using namespace mlir;
using namespace tilelang;

// TableGen-generated operation definitions (builders, parse/print, etc.).
#define GET_OP_CLASSES
#include "TileLang/IR/TileLangOps.cpp.inc"

//===----------------------------------------------------------------------===//
// CopyOp verification
//===----------------------------------------------------------------------===//

LogicalResult CopyOp::verify() {
  // Both src and dest must be memref types.
  auto srcType = llvm::dyn_cast<MemRefType>(getSrc().getType());
  auto destType = llvm::dyn_cast<MemRefType>(getDest().getType());

  if (!srcType) {
    return emitOpError("source operand must be a memref type, got ")
           << getSrc().getType();
  }
  if (!destType) {
    return emitOpError("destination operand must be a memref type, got ")
           << getDest().getType();
  }

  // Element types must match.
  if (srcType.getElementType() != destType.getElementType()) {
    return emitOpError("source and destination element types must match: ")
           << srcType.getElementType() << " vs " << destType.getElementType();
  }

  // If split_dim is present, it must be non-negative.
  if (auto splitDimAttr = getSplitDimAttr()) {
    int64_t splitDim = splitDimAttr.getValue().getSExtValue();
    if (splitDim < 0) {
      return emitOpError("split_dim must be non-negative, got ") << splitDim;
    }
  }

  // Both memrefs must have the same number of elements.
  if (srcType.hasStaticShape() && destType.hasStaticShape()) {
    int64_t srcElems = srcType.getNumElements();
    int64_t destElems = destType.getNumElements();
    if (srcElems != destElems) {
      return emitOpError("source and destination must have the same number "
                         "of elements: ")
             << srcElems << " vs " << destElems;
    }
  }

  return success();
}

//===----------------------------------------------------------------------===//
// GemmOp verification
//===----------------------------------------------------------------------===//

LogicalResult GemmOp::verify() {
  // All three operands must be memref types.
  auto aType = llvm::dyn_cast<MemRefType>(getA().getType());
  auto bType = llvm::dyn_cast<MemRefType>(getB().getType());
  auto cType = llvm::dyn_cast<MemRefType>(getC().getType());

  if (!aType) {
    return emitOpError("operand 'a' must be a memref type, got ")
           << getA().getType();
  }
  if (!bType) {
    return emitOpError("operand 'b' must be a memref type, got ")
           << getB().getType();
  }
  if (!cType) {
    return emitOpError("operand 'c' must be a memref type, got ")
           << getC().getType();
  }

  // Element types must be consistent.
  Type elemA = aType.getElementType();
  Type elemB = bType.getElementType();
  Type elemC = cType.getElementType();
  if (elemA != elemB || elemA != elemC) {
    return emitOpError("all operand element types must match: ")
           << elemA << ", " << elemB << ", " << elemC;
  }

  return success();
}

//===----------------------------------------------------------------------===//
// ScopeOp verification
//===----------------------------------------------------------------------===//

LogicalResult ScopeOp::verify() {
  // ScopeOp must have exactly one region (body).
  if (getBody().empty()) {
    return emitOpError("body region must not be empty");
  }

  // The body region should have at least one block.
  Block &bodyBlock = getBody().front();
  if (bodyBlock.empty()) {
    return emitOpError("body region's first block must not be empty");
  }

  // simd_attr, if present, must be a non-empty string.
  if (auto simdAttr = getSimdAttrAttr()) {
    StringRef simdVal = simdAttr.getValue();
    if (simdVal.empty()) {
      return emitOpError("simd_attr must not be an empty string");
    }
  }

  return success();
}