# Autogenerated-equivalent pattern for TileLangIR custom dialect.
# Hand-written to avoid mlir-tblgen dependency.

from mlir.dialects._ods_common import _cext as _ods_cext
from mlir.dialects._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Any as _Any, Sequence as _Sequence, Union as _Union, Optional as _Optional


# ---------------------------------------------------------------------------
# Dialect
# ---------------------------------------------------------------------------

@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
    DIALECT_NAMESPACE = "tilelang"


# ===========================================================================
# tilelang.copy
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class CopyOp(_ods_ir.OpView):
    OPERATION_NAME = "tilelang.copy"

    _ODS_REGIONS = (2, True)

    def __init__(
        self,
        *,
        split_dim: _Optional[int] = None,
        transpose: _Optional[bool] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        if split_dim is not None:
            attributes["split_dim"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), split_dim
            )
        if transpose:
            attributes["transpose"] = _ods_ir.UnitAttr.get(
                _ods_get_default_loc_context(loc)
            )
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,  # _ODS_OPERAND_SEGMENTS
            None,  # _ODS_RESULT_SEGMENTS
            attributes=attributes,
            results=[],
            operands=[],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def source(self) -> _ods_ir.Region:
        return self.regions[0]

    @builtins.property
    def dest(self) -> _ods_ir.Region:
        return self.regions[1]

    @builtins.property
    def split_dim(self) -> _Optional[int]:
        if "split_dim" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["split_dim"]).value

    @split_dim.setter
    def split_dim(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["split_dim"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "split_dim" in self.operation.attributes:
            del self.operation.attributes["split_dim"]

    @builtins.property
    def transpose(self) -> bool:
        return "transpose" in self.operation.attributes

    @transpose.setter
    def transpose(self, value: bool):
        if value:
            self.operation.attributes["transpose"] = _ods_ir.UnitAttr.get()
        elif "transpose" in self.operation.attributes:
            del self.operation.attributes["transpose"]


# ===========================================================================
# tilelang.gemm
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class GemmOp(_ods_ir.OpView):
    OPERATION_NAME = "tilelang.gemm"

    _ODS_REGIONS = (3, True)

    def __init__(
        self,
        *,
        transpose_a: _Optional[bool] = None,
        transpose_b: _Optional[bool] = None,
        m: _Optional[int] = None,
        n: _Optional[int] = None,
        k: _Optional[int] = None,
        clear_accum: _Optional[bool] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        _ods_context = _ods_get_default_loc_context(loc)
        if transpose_a:
            attributes["transpose_a"] = _ods_ir.UnitAttr.get(_ods_context)
        if transpose_b:
            attributes["transpose_b"] = _ods_ir.UnitAttr.get(_ods_context)
        if m is not None:
            attributes["m"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), m
            )
        if n is not None:
            attributes["n"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), n
            )
        if k is not None:
            attributes["k"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), k
            )
        if clear_accum:
            attributes["clear_accum"] = _ods_ir.UnitAttr.get(_ods_context)
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes=attributes,
            results=[],
            operands=[],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def a_region(self) -> _ods_ir.Region:
        return self.regions[0]

    @builtins.property
    def b_region(self) -> _ods_ir.Region:
        return self.regions[1]

    @builtins.property
    def c_region(self) -> _ods_ir.Region:
        return self.regions[2]

    @builtins.property
    def transpose_a(self) -> bool:
        return "transpose_a" in self.operation.attributes

    @transpose_a.setter
    def transpose_a(self, value: bool):
        if value:
            self.operation.attributes["transpose_a"] = _ods_ir.UnitAttr.get()
        elif "transpose_a" in self.operation.attributes:
            del self.operation.attributes["transpose_a"]

    @builtins.property
    def transpose_b(self) -> bool:
        return "transpose_b" in self.operation.attributes

    @transpose_b.setter
    def transpose_b(self, value: bool):
        if value:
            self.operation.attributes["transpose_b"] = _ods_ir.UnitAttr.get()
        elif "transpose_b" in self.operation.attributes:
            del self.operation.attributes["transpose_b"]

    @builtins.property
    def m(self) -> _Optional[int]:
        if "m" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["m"]).value

    @m.setter
    def m(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["m"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "m" in self.operation.attributes:
            del self.operation.attributes["m"]

    @builtins.property
    def n(self) -> _Optional[int]:
        if "n" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["n"]).value

    @n.setter
    def n(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["n"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "n" in self.operation.attributes:
            del self.operation.attributes["n"]

    @builtins.property
    def k(self) -> _Optional[int]:
        if "k" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["k"]).value

    @k.setter
    def k(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["k"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "k" in self.operation.attributes:
            del self.operation.attributes["k"]

    @builtins.property
    def clear_accum(self) -> bool:
        return "clear_accum" in self.operation.attributes

    @clear_accum.setter
    def clear_accum(self, value: bool):
        if value:
            self.operation.attributes["clear_accum"] = _ods_ir.UnitAttr.get()
        elif "clear_accum" in self.operation.attributes:
            del self.operation.attributes["clear_accum"]


# ===========================================================================
# tilelang.launch_thread
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class LaunchThreadOp(_ods_ir.OpView):
    OPERATION_NAME = "tilelang.launch_thread"

    _ODS_REGIONS = (1, True)

    def __init__(
        self,
        *,
        thread_tag: _Optional[str] = None,
        extent: _Optional[int] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        if thread_tag is not None:
            attributes["thread_tag"] = _ods_ir.StringAttr.get(thread_tag)
        if extent is not None:
            attributes["extent"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), extent
            )
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes=attributes,
            results=[],
            operands=[],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def body(self) -> _ods_ir.Region:
        return self.regions[0]

    @builtins.property
    def thread_tag(self) -> _Optional[str]:
        if "thread_tag" not in self.operation.attributes:
            return None
        return _ods_ir.StringAttr(self.operation.attributes["thread_tag"]).value

    @thread_tag.setter
    def thread_tag(self, value: _Optional[str]):
        if value is not None:
            self.operation.attributes["thread_tag"] = _ods_ir.StringAttr.get(value)
        elif "thread_tag" in self.operation.attributes:
            del self.operation.attributes["thread_tag"]

    @builtins.property
    def extent(self) -> _Optional[int]:
        if "extent" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["extent"]).value

    @extent.setter
    def extent(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["extent"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "extent" in self.operation.attributes:
            del self.operation.attributes["extent"]