# Autogenerated-equivalent pattern for TileLangIR custom dialect.
# Hand-written to avoid mlir-tblgen dependency.

from mlir.dialects._ods_common import _cext as _ods_cext
from mlir.dialects._ods_common import (
    get_default_loc_context as _ods_get_default_loc_context,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Optional as _Optional


# ---------------------------------------------------------------------------
# Dialect
# ---------------------------------------------------------------------------

@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
    DIALECT_NAMESPACE = "tilelang"


# ===========================================================================
# tilelang.copy
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class CopyOp(_ods_ir.OpView):
    """Copy between two memref/view SSA values.

    Assembly (unregistered dialect form)::

        "tilelang.copy"(%src, %dst) : (memref<...>, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.copy"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src,
        dest,
        *,
        split_dim: _Optional[int] = None,
        transpose: _Optional[bool] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        if split_dim is not None:
            attributes["split_dim"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), split_dim
            )
        if transpose:
            attributes["transpose"] = _ods_ir.UnitAttr.get(
                _ods_get_default_loc_context(loc)
            )
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,  # _ODS_OPERAND_SEGMENTS
            None,  # _ODS_RESULT_SEGMENTS
            attributes=attributes,
            results=[],
            operands=[src, dest],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src(self):
        return self.operation.operands[0]

    @builtins.property
    def dest(self):
        return self.operation.operands[1]

    @builtins.property
    def split_dim(self) -> _Optional[int]:
        if "split_dim" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["split_dim"]).value

    @split_dim.setter
    def split_dim(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["split_dim"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "split_dim" in self.operation.attributes:
            del self.operation.attributes["split_dim"]

    @builtins.property
    def transpose(self) -> bool:
        return "transpose" in self.operation.attributes

    @transpose.setter
    def transpose(self, value: bool):
        if value:
            self.operation.attributes["transpose"] = _ods_ir.UnitAttr.get()
        elif "transpose" in self.operation.attributes:
            del self.operation.attributes["transpose"]


# ===========================================================================
# tilelang.gemm
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class GemmOp(_ods_ir.OpView):
    OPERATION_NAME = "tilelang.gemm"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        a,
        b,
        c,
        *,
        transpose_a: _Optional[bool] = None,
        transpose_b: _Optional[bool] = None,
        clear_accum: _Optional[bool] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        _ods_context = _ods_get_default_loc_context(loc)
        if transpose_a:
            attributes["transpose_a"] = _ods_ir.UnitAttr.get(_ods_context)
        if transpose_b:
            attributes["transpose_b"] = _ods_ir.UnitAttr.get(_ods_context)
        if clear_accum:
            attributes["clear_accum"] = _ods_ir.UnitAttr.get(_ods_context)
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes=attributes,
            results=[],
            operands=[a, b, c],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def a(self):
        return self.operation.operands[0]

    @builtins.property
    def b(self):
        return self.operation.operands[1]

    @builtins.property
    def c(self):
        return self.operation.operands[2]

    @builtins.property
    def transpose_a(self) -> bool:
        return "transpose_a" in self.operation.attributes

    @transpose_a.setter
    def transpose_a(self, value: bool):
        if value:
            self.operation.attributes["transpose_a"] = _ods_ir.UnitAttr.get()
        elif "transpose_a" in self.operation.attributes:
            del self.operation.attributes["transpose_a"]

    @builtins.property
    def transpose_b(self) -> bool:
        return "transpose_b" in self.operation.attributes

    @transpose_b.setter
    def transpose_b(self, value: bool):
        if value:
            self.operation.attributes["transpose_b"] = _ods_ir.UnitAttr.get()
        elif "transpose_b" in self.operation.attributes:
            del self.operation.attributes["transpose_b"]

    @builtins.property
    def clear_accum(self) -> bool:
        return "clear_accum" in self.operation.attributes

    @clear_accum.setter
    def clear_accum(self, value: bool):
        if value:
            self.operation.attributes["clear_accum"] = _ods_ir.UnitAttr.get()
        elif "clear_accum" in self.operation.attributes:
            del self.operation.attributes["clear_accum"]


# ===========================================================================
# tilelang.scope
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class ScopeOp(_ods_ir.OpView):
    """Scope region with explicit default, SIMD, or SIMT execution mode.

    Assembly (unregistered dialect form)::

        "tilelang.scope"() ({ ... }) {
          mode = #tilelang.scope_mode<simt>, threads = 128 : ui32
        } : () -> ()
    """

    OPERATION_NAME = "tilelang.scope"

    _ODS_REGIONS = (1, True)

    def __init__(
        self,
        *,
        mode: str,
        threads: _Optional[int] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        if mode not in ("default", "simd", "simt"):
            raise ValueError(
                "ScopeOp mode must be one of 'default', 'simd', or 'simt', "
                f"got {mode!r}"
            )
        if mode == "simt" and threads is None:
            raise ValueError("ScopeOp SIMT mode requires threads")
        if mode != "simt" and threads is not None:
            raise ValueError("ScopeOp threads are only valid in SIMT mode")
        attributes["mode"] = _ods_ir.Attribute.parse(
            f"#tilelang.scope_mode<{mode}>"
        )
        if threads is not None:
            if isinstance(threads, bool) or not isinstance(threads, int):
                raise TypeError("ScopeOp threads must be a uint32 integer")
            if not 1 <= threads <= (1 << 32) - 1:
                raise ValueError(
                    "ScopeOp threads must be in the uint32 range "
                    "[1, 4294967295]"
                )
            attributes["threads"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_unsigned(32), threads
            )
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes=attributes,
            results=[],
            operands=[],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def body(self) -> _ods_ir.Region:
        return self.regions[0]

    @builtins.property
    def mode(self):
        return self.operation.attributes["mode"]

    @builtins.property
    def threads(self) -> _Optional[int]:
        if "threads" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["threads"]).value


# ===========================================================================
# tilelang.scope_yield
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class ScopeYieldOp(_ods_ir.OpView):
    """Terminator for ``tilelang.scope`` regions."""

    OPERATION_NAME = "tilelang.scope_yield"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        *,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes={},
            results=[],
            operands=[],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )


# ===========================================================================
# tilelang.vcvt
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class VcvtOp(_ods_ir.OpView):
    """Elementwise type conversion between two memref SSA values.

    ``src_dtype``/``dst_dtype`` preserve the frontend TIRX dtype names (e.g.
    ``"uint8"``/``"float32"``) whose signedness is lost in signless memref
    element types. The backend reconstructs the cast ``type_fn`` from them.

    Assembly (unregistered dialect form)::

        "tilelang.vcvt"(%src, %dst) {src_dtype = "float32", dst_dtype = "float16"}
            : (memref<...>, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.vcvt"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src,
        dst,
        *,
        src_dtype: str,
        dst_dtype: str,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes={
                "src_dtype": _ods_ir.StringAttr.get(src_dtype),
                "dst_dtype": _ods_ir.StringAttr.get(dst_dtype),
            },
            results=[],
            operands=[src, dst],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src(self):
        return self.operation.operands[0]

    @builtins.property
    def dst(self):
        return self.operation.operands[1]

    @builtins.property
    def src_dtype(self) -> str:
        return _ods_ir.StringAttr(self.operation.attributes["src_dtype"]).value

    @builtins.property
    def dst_dtype(self) -> str:
        return _ods_ir.StringAttr(self.operation.attributes["dst_dtype"]).value


# ===========================================================================
# tilelang.vexpdif
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class VexpdifOp(_ods_ir.OpView):
    """Elementwise ``exp(src0 - src1)`` on three memref SSA values.

    Assembly (unregistered dialect form)::

        "tilelang.vexpdif"(%src0, %src1, %dst)
            : (memref<...>, memref<...>, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.vexpdif"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src0,
        src1,
        dst,
        *,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes={},
            results=[],
            operands=[src0, src1, dst],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src0(self):
        return self.operation.operands[0]

    @builtins.property
    def src1(self):
        return self.operation.operands[1]

    @builtins.property
    def dst(self):
        return self.operation.operands[2]


# ===========================================================================
# tilelang.vmuls
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class VmulsOp(_ods_ir.OpView):
    """Elementwise ``src * scalar`` on a memref source and a scalar SSA value.

    The scalar is an explicit operand rather than a region free variable.

    Assembly (unregistered dialect form)::

        "tilelang.vmuls"(%src, %scalar, %dst)
            : (memref<...>, f32, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.vmuls"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src,
        scalar,
        dst,
        *,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes={},
            results=[],
            operands=[src, scalar, dst],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src(self):
        return self.operation.operands[0]

    @builtins.property
    def scalar(self):
        return self.operation.operands[1]

    @builtins.property
    def dst(self):
        return self.operation.operands[2]


# ===========================================================================
# tilelang.vmax
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class VmaxOp(_ods_ir.OpView):
    """Elementwise maximum of two memref SSA values.

    ``dtype`` preserves the frontend TIRX dtype name (e.g. ``"uint8"``,
    ``"float32"``) so the backend can pick the right signedness.

    Assembly (unregistered dialect form)::

        "tilelang.vmax"(%src0, %src1, %dst) {dtype = "float32"}
            : (memref<...>, memref<...>, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.vmax"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src0,
        src1,
        dst,
        *,
        dtype: str,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes={"dtype": _ods_ir.StringAttr.get(dtype)},
            results=[],
            operands=[src0, src1, dst],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src0(self):
        return self.operation.operands[0]

    @builtins.property
    def src1(self):
        return self.operation.operands[1]

    @builtins.property
    def dst(self):
        return self.operation.operands[2]

    @builtins.property
    def dtype(self) -> str:
        return _ods_ir.StringAttr(self.operation.attributes["dtype"]).value


# ===========================================================================
# tilelang.vsub
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class VsubOp(_ods_ir.OpView):
    """Elementwise subtraction of two memref SSA values.

    Broadcast relationships are inferred from the operand memref shapes; the
    backend inserts a ``npu.broadcast`` when a reaching vector definition has a
    different shape than the destination fragment.

    Assembly (unregistered dialect form)::

        "tilelang.vsub"(%src0, %src1, %dst)
            : (memref<...>, memref<...>, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.vsub"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src0,
        src1,
        dst,
        *,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes={},
            results=[],
            operands=[src0, src1, dst],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src0(self):
        return self.operation.operands[0]

    @builtins.property
    def src1(self):
        return self.operation.operands[1]

    @builtins.property
    def dst(self):
        return self.operation.operands[2]
