# Autogenerated-equivalent pattern for TileLangIR custom dialect.
# Hand-written to avoid mlir-tblgen dependency.

from mlir.dialects._ods_common import _cext as _ods_cext
from mlir.dialects._ods_common import (
    get_default_loc_context as _ods_get_default_loc_context,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Optional as _Optional


# ---------------------------------------------------------------------------
# Dialect
# ---------------------------------------------------------------------------

@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
    DIALECT_NAMESPACE = "tilelang"


# ===========================================================================
# tilelang.copy
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class CopyOp(_ods_ir.OpView):
    """Copy between two memref/view SSA values.

    Assembly (unregistered dialect form)::

        "tilelang.copy"(%src, %dst) : (memref<...>, memref<...>) -> ()
    """

    OPERATION_NAME = "tilelang.copy"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        src,
        dest,
        *,
        split_dim: _Optional[int] = None,
        transpose: _Optional[bool] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        if split_dim is not None:
            attributes["split_dim"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), split_dim
            )
        if transpose:
            attributes["transpose"] = _ods_ir.UnitAttr.get(
                _ods_get_default_loc_context(loc)
            )
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,  # _ODS_OPERAND_SEGMENTS
            None,  # _ODS_RESULT_SEGMENTS
            attributes=attributes,
            results=[],
            operands=[src, dest],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def src(self):
        return self.operation.operands[0]

    @builtins.property
    def dest(self):
        return self.operation.operands[1]

    @builtins.property
    def split_dim(self) -> _Optional[int]:
        if "split_dim" not in self.operation.attributes:
            return None
        return _ods_ir.IntegerAttr(self.operation.attributes["split_dim"]).value

    @split_dim.setter
    def split_dim(self, value: _Optional[int]):
        if value is not None:
            self.operation.attributes["split_dim"] = _ods_ir.IntegerAttr.get(
                _ods_ir.IntegerType.get_signless(64), value
            )
        elif "split_dim" in self.operation.attributes:
            del self.operation.attributes["split_dim"]

    @builtins.property
    def transpose(self) -> bool:
        return "transpose" in self.operation.attributes

    @transpose.setter
    def transpose(self, value: bool):
        if value:
            self.operation.attributes["transpose"] = _ods_ir.UnitAttr.get()
        elif "transpose" in self.operation.attributes:
            del self.operation.attributes["transpose"]


# ===========================================================================
# tilelang.gemm
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class GemmOp(_ods_ir.OpView):
    OPERATION_NAME = "tilelang.gemm"

    _ODS_REGIONS = (0, True)

    def __init__(
        self,
        a,
        b,
        c,
        *,
        transpose_a: _Optional[bool] = None,
        transpose_b: _Optional[bool] = None,
        clear_accum: _Optional[bool] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        _ods_context = _ods_get_default_loc_context(loc)
        if transpose_a:
            attributes["transpose_a"] = _ods_ir.UnitAttr.get(_ods_context)
        if transpose_b:
            attributes["transpose_b"] = _ods_ir.UnitAttr.get(_ods_context)
        if clear_accum:
            attributes["clear_accum"] = _ods_ir.UnitAttr.get(_ods_context)
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes=attributes,
            results=[],
            operands=[a, b, c],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def a(self):
        return self.operation.operands[0]

    @builtins.property
    def b(self):
        return self.operation.operands[1]

    @builtins.property
    def c(self):
        return self.operation.operands[2]

    @builtins.property
    def transpose_a(self) -> bool:
        return "transpose_a" in self.operation.attributes

    @transpose_a.setter
    def transpose_a(self, value: bool):
        if value:
            self.operation.attributes["transpose_a"] = _ods_ir.UnitAttr.get()
        elif "transpose_a" in self.operation.attributes:
            del self.operation.attributes["transpose_a"]

    @builtins.property
    def transpose_b(self) -> bool:
        return "transpose_b" in self.operation.attributes

    @transpose_b.setter
    def transpose_b(self, value: bool):
        if value:
            self.operation.attributes["transpose_b"] = _ods_ir.UnitAttr.get()
        elif "transpose_b" in self.operation.attributes:
            del self.operation.attributes["transpose_b"]

    @builtins.property
    def clear_accum(self) -> bool:
        return "clear_accum" in self.operation.attributes

    @clear_accum.setter
    def clear_accum(self, value: bool):
        if value:
            self.operation.attributes["clear_accum"] = _ods_ir.UnitAttr.get()
        elif "clear_accum" in self.operation.attributes:
            del self.operation.attributes["clear_accum"]


# ===========================================================================
# tilelang.scope
# ===========================================================================

@_ods_cext.register_operation(_Dialect)
class ScopeOp(_ods_ir.OpView):
    """Scope region used for SimdVF and similar frontend scopes.

    Assembly (unregistered dialect form)::

        "tilelang.scope"() ({ ... }) {simd_attr = "simd"} : () -> ()
    """

    OPERATION_NAME = "tilelang.scope"

    _ODS_REGIONS = (1, True)

    def __init__(
        self,
        *,
        simd_attr: _Optional[str] = None,
        loc: _Optional[_ods_ir.Location] = None,
        ip: _Optional[_ods_ir.InsertionPoint] = None,
    ):
        attributes: dict = {}
        if simd_attr is not None:
            attributes["simd_attr"] = _ods_ir.StringAttr.get(simd_attr)
        super().__init__(
            self.OPERATION_NAME,
            self._ODS_REGIONS,
            None,
            None,
            attributes=attributes,
            results=[],
            operands=[],
            successors=None,
            regions=None,
            loc=loc,
            ip=ip,
        )

    @builtins.property
    def body(self) -> _ods_ir.Region:
        return self.regions[0]

    @builtins.property
    def simd_attr(self) -> _Optional[str]:
        if "simd_attr" not in self.operation.attributes:
            return None
        return _ods_ir.StringAttr(self.operation.attributes["simd_attr"]).value

    @simd_attr.setter
    def simd_attr(self, value: _Optional[str]):
        if value is not None:
            self.operation.attributes["simd_attr"] = _ods_ir.StringAttr.get(value)
        elif "simd_attr" in self.operation.attributes:
            del self.operation.attributes["simd_attr"]
