"""TileLangIR ``tilelang.vcvt`` codegen tests.

Verifies that ``T.vcvt`` in the DSL lowers to a ``linalg.generic`` structured
op whose body contains the expected ``arith`` cast operation.  These are pure
IR codegen tests: they call ``tilelang.lower(..., target="tile")`` and assert
on the generated MLIR source string.  No Ascend hardware required.

The four cast categories exercised here mirror the dispatch tree in
``TileLangIRTranslator._build_arith_cast``:

  * float -> float : ``arith.truncf`` / ``arith.extf`` / ``arith.bitcast``
  * float -> int   : ``arith.fptosi`` / ``arith.fptoui``
  * int   -> float : ``arith.sitofp`` / ``arith.uitofp``
  * int   -> int   : ``arith.trunci`` / ``arith.extsi`` / ``arith.extui``
"""

from __future__ import annotations

import re

import tilelang
import tilelang.language as T
import tilelang.testing


def _vcvt_kernel(
    VL: int = 64,
    src_dtype: str = "float32",
    dst_dtype: str = "float16",
):
    """Build a minimal kernel that casts a 1-D fragment ``src -> dst``.

    Only the ``T.vcvt`` call is exercised; the surrounding ``T.copy`` ops feed
    the source fragment and drain the destination fragment so that the TIRX IR
    shape matches a realistic kernel.
    """

    @T.prim_func
    def main(
        A: T.Tensor((1, VL), src_dtype),
        B: T.Tensor((1, VL), dst_dtype),
    ):
        with T.Kernel(1):
            a_shared = T.alloc_shared((1, VL), src_dtype)
            b_shared = T.alloc_shared((1, VL), dst_dtype)
            T.copy(A[0:1, 0:VL], a_shared)

            with T.SimdVF():
                a_frag = T.alloc_fragment((VL,), src_dtype)
                b_frag = T.alloc_fragment((VL,), dst_dtype)
                T.copy(a_shared[0, 0:VL], a_frag)
                T.vcvt(a_frag, b_frag, dst_dtype)
                T.copy(b_frag, b_shared[0, 0:VL])

            T.copy(b_shared, B[0:1, 0:VL])

    return main


def _lower_to_tile_source(kernel) -> str:
    """Lower ``kernel`` to tile target and return the generated MLIR source."""
    artifact = tilelang.lower(kernel, target="tile")
    return str(artifact.kernel_source)


def _extract_vcvt_block(source: str) -> str:
    """Extract the ``linalg.generic`` block generated by ``T.vcvt``.

    A vcvt-generated generic op has exactly one ``arith.*`` cast in its body.
    Returns the substring from ``linalg.generic`` through the closing brace.
    """
    match = re.search(
        r"linalg\.generic\s*\{[^}]*\}\s*ins\([^)]*\)\s*outs\([^)]*\)\s*\{[^}]*\}",
        source,
        re.DOTALL,
    )
    assert match is not None, (
        "Expected a `linalg.generic` op in the generated MLIR, but none was "
        f"found.\nSource:\n{source}"
    )
    return match.group(0)


def _assert_arith_op(vcvt_block: str, op_name: str) -> None:
    """Assert that ``arith.<op_name>`` appears inside the vcvt block."""
    full = f"arith.{op_name}"
    assert full in vcvt_block, (
        f"Expected `{full}` in the vcvt linalg.generic body, but it is "
        f"missing.\nBlock:\n{vcvt_block}"
    )


def _assert_no_arith_op(vcvt_block: str, op_name: str) -> None:
    """Assert that ``arith.<op_name>`` does NOT appear inside the vcvt block."""
    full = f"arith.{op_name}"
    assert full not in vcvt_block, (
        f"Did not expect `{full}` in the vcvt linalg.generic body, but it is "
        f"present.\nBlock:\n{vcvt_block}"
    )


# ---------------------------------------------------------------------------
# float -> float : narrow / widen / reinterpret
# ---------------------------------------------------------------------------

@tilelang.testing.requires_package("mlir")
def test_vcvt_f32_to_f16_emits_truncf():
    """f32 -> f16 is a narrowing cast, must emit ``arith.truncf``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="float16")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "truncf")


@tilelang.testing.requires_package("mlir")
def test_vcvt_f16_to_f32_emits_extf():
    """f16 -> f32 is a widening cast, must emit ``arith.extf``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float16", dst_dtype="float32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "extf")


@tilelang.testing.requires_package("mlir")
def test_vcvt_f32_to_bf16_emits_truncf():
    """f32 -> bf16 is a narrowing cast (bf16 is 16-bit), must emit ``arith.truncf``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="bfloat16")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "truncf")


@tilelang.testing.requires_package("mlir")
def test_vcvt_bf16_to_f32_emits_extf():
    """bf16 -> f32 is a widening cast, must emit ``arith.extf``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="bfloat16", dst_dtype="float32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "extf")


@tilelang.testing.requires_package("mlir")
def test_vcvt_bf16_to_f16_emits_extf_then_truncf():
    """bf16 -> f16 is same-width but different float type, must round-trip
    through f32 (``extf`` then ``truncf``), not ``bitcast``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="bfloat16", dst_dtype="float16")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "extf")
    _assert_arith_op(block, "truncf")
    _assert_no_arith_op(block, "bitcast")


@tilelang.testing.requires_package("mlir")
def test_vcvt_f16_to_bf16_emits_extf_then_truncf():
    """f16 -> bf16 is same-width but different float type, must round-trip
    through f32 (``extf`` then ``truncf``), not ``bitcast``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float16", dst_dtype="bfloat16")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "extf")
    _assert_arith_op(block, "truncf")
    _assert_no_arith_op(block, "bitcast")


# ---------------------------------------------------------------------------
# float -> int : signed / unsigned
# ---------------------------------------------------------------------------

@tilelang.testing.requires_package("mlir")
def test_vcvt_f32_to_int32_emits_fptosi():
    """f32 -> int32 must emit ``arith.fptosi``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="int32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "fptosi")
    _assert_no_arith_op(block, "fptoui")


@tilelang.testing.requires_package("mlir")
def test_vcvt_f32_to_uint8_emits_fptoui():
    """f32 -> uint8 must emit ``arith.fptoui`` (unsigned destination)."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="uint8")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "fptoui")
    _assert_no_arith_op(block, "fptosi")


# ---------------------------------------------------------------------------
# int -> float : always sitofp (signless source, signed default)
# ---------------------------------------------------------------------------

@tilelang.testing.requires_package("mlir")
def test_vcvt_int32_to_f32_emits_sitofp():
    """int32 -> f32 must emit ``arith.sitofp``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="int32", dst_dtype="float32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "sitofp")


@tilelang.testing.requires_package("mlir")
def test_vcvt_int8_to_f16_emits_sitofp():
    """int8 -> f16 must emit ``arith.sitofp``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="int8", dst_dtype="float16")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "sitofp")


# ---------------------------------------------------------------------------
# int -> int : narrow / sign-extend
# ---------------------------------------------------------------------------

@tilelang.testing.requires_package("mlir")
def test_vcvt_int32_to_int8_emits_trunci():
    """int32 -> int8 is a narrowing cast, must emit ``arith.trunci``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="int32", dst_dtype="int8")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "trunci")


@tilelang.testing.requires_package("mlir")
def test_vcvt_int8_to_int32_emits_extsi():
    """int8 -> int32 is a sign-extending cast, must emit ``arith.extsi``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="int8", dst_dtype="int32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "extsi")


@tilelang.testing.requires_package("mlir")
def test_vcvt_uint8_to_int32_emits_extui():
    """uint8 -> int32 is a zero-extending cast, must emit ``arith.extui``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="uint8", dst_dtype="int32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "extui")


@tilelang.testing.requires_package("mlir")
def test_vcvt_uint8_to_int8_emits_no_cast():
    """uint8 -> int8 is same bit-width; MLIR integers are signless so no
    cast op should be emitted (the input is yielded directly)."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="uint8", dst_dtype="int8")
    )
    block = _extract_vcvt_block(source)
    # No arith cast op should appear; the block only contains linalg.yield.
    assert "arith." not in block, (
        f"Expected no arith cast for same-width int->int.\nBlock:\n{block}"
    )
    assert "linalg.yield" in block, (
        f"Expected linalg.yield in block.\nBlock:\n{block}"
    )


@tilelang.testing.requires_package("mlir")
def test_vcvt_uint8_to_float32_emits_uitofp():
    """uint8 -> float32 must emit ``arith.uitofp`` (not sitofp)."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="uint8", dst_dtype="float32")
    )
    block = _extract_vcvt_block(source)
    _assert_arith_op(block, "uitofp")


# ---------------------------------------------------------------------------
# Structural checks on the generated linalg.generic
# ---------------------------------------------------------------------------

@tilelang.testing.requires_package("mlir")
def test_vcvt_emits_linalg_generic_with_parallel_iterator():
    """The vcvt linalg.generic must use ``parallel`` iterator types."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="float16")
    )
    block = _extract_vcvt_block(source)
    assert '"parallel"' in block, (
        f"Expected `parallel` iterator type in vcvt block.\nBlock:\n{block}"
    )


@tilelang.testing.requires_package("mlir")
def test_vcvt_emits_linalg_yield():
    """The vcvt linalg.generic body must end with ``linalg.yield``."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="float16")
    )
    block = _extract_vcvt_block(source)
    assert "linalg.yield" in block, (
        f"Expected `linalg.yield` in vcvt block.\nBlock:\n{block}"
    )


@tilelang.testing.requires_package("mlir")
def test_vcvt_identity_affine_map():
    """The vcvt indexing map must be the identity ``(d0) -> (d0)`` for 1-D."""
    source = _lower_to_tile_source(
        _vcvt_kernel(src_dtype="float32", dst_dtype="float16")
    )
    # The identity map is printed as ``#map = affine_map<(d0) -> (d0)>`` at
    # module top level and referenced as ``#map`` inside the generic op.
    assert "affine_map<(d0) -> (d0)>" in source, (
        "Expected identity affine map `(d0) -> (d0)` for 1-D vcvt.\n"
        f"Source:\n{source}"
    )


if __name__ == "__main__":
    tilelang.testing.main()
